version: "3.8"

services:
  pgdb: 
    container_name: pgdb_ecommerce
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  esearch:
    container_name: search
    image: elasticsearch:7.14.2
    environment: 
      - discovery.type=single-node

    ports:
      - 9200:9200